server:
  port: 9999
spring:
  ai:
    ollama:
      base-url: http://localhost:11434 # 哦llama地址
      chat:
        model: deepseek-r1:1.5b # 模型
        options:
          temperature: 0.8 # 温度越高，回答越有创意
          top-p: 0.9 # 数值越高，回答越多样
          top-k: 100 # 数值越高，回答越多样

      embedding:
        model: nomic-embed-text:latest
    # 向量数据库配置
    vectorstore:
      elasticsearch:
        index-name: ollama-rag-embedding-index
        similarity: cosine
        dimensions: 768
      redis:
        index:

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    cn.kanyu: debug




