server:
  port: 9999
spring:
  ai:
    ollama:
      base-url: http://localhost:11434 # 哦llama地址
      chat:
        model: qwen3:0.6b # 模型
        options:
          temperature: 0.8 # 温度越高，回答越有创意
          top-p: 0.9 # 数值越高，回答越多样
          top-k: 100 # 数值越高，回答越多样
      embedding:
        options:
          model: qwen3:0.6b
    vectorstore:
      pgvector:
        index-type: NONE
        distance-type: cosine_distance
        dimensions: 2048
      redis:
        uri: redis://localhost:6379
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    cn.kanyu: debug




